# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: 4d7fec2fa767045e34dc2dead1dc77505a68e10e

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

mail:
    host: smtp.gmail.com
    port: 587
    username: traian.rusu92@gmail.com
    password: tiribomba1
    protocol: smtp
    tls: true
    auth: true
    from: traian.rusu92@gmail.com


swagger:
    title: SuntemEgali API
    description: SuntemEgali applications and beyond!
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
